-- Create the scores table
create table if not exists scores (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index for better performance
create index if not exists scores_score_idx on scores (score desc);

-- Enable read access for all users
create policy "Scores are viewable by everyone" on scores
for select using (true);

-- Enable insert access for all users
create policy "Users can insert their own scores" on scores
for insert with check (true);

-- Grant access to the table
grant usage on schema public to anon;
grant select on public.scores to anon;
grant insert on public.scores to anon;